-- ai-memory initialization SQL.
-- MySQL is the authoritative memory store. Qdrant points are derived from ai_memory_vector_task.

CREATE TABLE IF NOT EXISTS `ddl_history` (
    `script` varchar(500) NOT NULL COMMENT '脚本',
    `type` varchar(30) NOT NULL COMMENT '类型',
    `version` varchar(30) NOT NULL COMMENT '版本',
    PRIMARY KEY (`script`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='DDL 版本';

CREATE TABLE IF NOT EXISTS `undo_log` (
    `branch_id` bigint NOT NULL COMMENT 'branch transaction id',
    `xid` varchar(128) NOT NULL COMMENT 'global transaction id',
    `context` varchar(128) NOT NULL COMMENT 'undo_log context,such as serialization',
    `rollback_info` longblob NOT NULL COMMENT 'rollback info',
    `log_status` int NOT NULL COMMENT '0:normal status,1:defense status',
    `log_created` datetime(6) NOT NULL COMMENT 'create datetime',
    `log_modified` datetime(6) NOT NULL COMMENT 'modify datetime',
    UNIQUE KEY `ux_undo_log` (`xid`, `branch_id`),
    KEY `ix_log_created` (`log_created`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='AT transaction mode undo table';

CREATE TABLE IF NOT EXISTS `ai_memory_short_message` (
    `id` varchar(64) NOT NULL COMMENT '主键ID',
    `conversation_id` varchar(128) NOT NULL COMMENT '会话ID',
    `source_tenant_id` varchar(64) DEFAULT NULL COMMENT '来源业务租户ID',
    `patient_id` varchar(64) DEFAULT NULL COMMENT '患者ID',
    `user_id` varchar(64) DEFAULT NULL COMMENT '调用方用户ID',
    `caller` varchar(64) NOT NULL COMMENT '调用方',
    `message_role` varchar(24) NOT NULL COMMENT '消息角色 user/assistant/system',
    `content` longtext NOT NULL COMMENT '短期记忆原文',
    `token_estimate` int DEFAULT NULL COMMENT '估算 token 数',
    `occurred_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '消息发生时间',
    `code` varchar(255) DEFAULT NULL COMMENT '编码',
    `description` varchar(255) DEFAULT NULL COMMENT '说明',
    `create_date_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_name` varchar(255) DEFAULT NULL COMMENT '创建人',
    `modify_date_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `modify_name` varchar(255) DEFAULT NULL COMMENT '修改人',
    `is_delete` bit(1) DEFAULT b'0' COMMENT '删除状态',
    `label` varchar(255) DEFAULT NULL COMMENT '标签',
    `sorting` int DEFAULT '0' COMMENT '排序',
    `version` int DEFAULT '1' COMMENT '版本号',
    `tenant_id` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '100' COMMENT 'Kellen 内部租户ID',
    PRIMARY KEY (`id`),
    KEY `idx_ai_memory_short_message_conversation_time` (`conversation_id`, `occurred_at`),
    KEY `idx_ai_memory_short_message_patient` (`patient_id`, `source_tenant_id`, `occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='AI 短期会话记忆窗口';

CREATE TABLE IF NOT EXISTS `ai_memory_short_summary` (
    `id` varchar(64) NOT NULL COMMENT '主键ID',
    `conversation_id` varchar(128) NOT NULL COMMENT '会话ID',
    `source_tenant_id` varchar(64) DEFAULT NULL COMMENT '来源业务租户ID',
    `patient_id` varchar(64) DEFAULT NULL COMMENT '患者ID',
    `summary_text` longtext NOT NULL COMMENT '会话滚动摘要',
    `summary_version` int NOT NULL DEFAULT '1' COMMENT '摘要版本',
    `summarized_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '摘要更新时间',
    `code` varchar(255) DEFAULT NULL COMMENT '编码',
    `description` varchar(255) DEFAULT NULL COMMENT '说明',
    `create_date_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_name` varchar(255) DEFAULT NULL COMMENT '创建人',
    `modify_date_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `modify_name` varchar(255) DEFAULT NULL COMMENT '修改人',
    `is_delete` bit(1) DEFAULT b'0' COMMENT '删除状态',
    `label` varchar(255) DEFAULT NULL COMMENT '标签',
    `sorting` int DEFAULT '0' COMMENT '排序',
    `version` int DEFAULT '1' COMMENT '版本号',
    `tenant_id` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '100' COMMENT 'Kellen 内部租户ID',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_memory_short_summary_conversation` (`conversation_id`),
    KEY `idx_ai_memory_short_summary_patient` (`patient_id`, `source_tenant_id`, `summarized_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='AI 短期会话滚动摘要';

CREATE TABLE IF NOT EXISTS `ai_memory_long_fact` (
    `id` varchar(64) NOT NULL COMMENT '主键ID',
    `patient_id` varchar(64) NOT NULL COMMENT '患者ID',
    `source_tenant_id` varchar(64) NOT NULL COMMENT '来源业务租户ID',
    `memory_type` varchar(64) NOT NULL COMMENT '记忆类型',
    `memory_key` varchar(160) NOT NULL COMMENT '同患者同来源下稳定记忆键',
    `title` varchar(255) NOT NULL COMMENT '记忆标题',
    `content` longtext NOT NULL COMMENT '可注入模型的事实文本',
    `facts_json` longtext DEFAULT NULL COMMENT '结构化事实 JSON',
    `source_type` varchar(64) DEFAULT NULL COMMENT '来源类型',
    `source_id` varchar(128) DEFAULT NULL COMMENT '来源业务ID',
    `confidence` double NOT NULL DEFAULT '0' COMMENT '事实置信度',
    `status` varchar(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态 ACTIVE/ARCHIVED/MASKED/DELETED/REVOKED',
    `sensitivity_level` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '敏感级别',
    `authorization_scope` varchar(128) DEFAULT NULL COMMENT '授权范围',
    `embedding_status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '向量同步状态',
    `vector_collection` varchar(128) DEFAULT NULL COMMENT 'Qdrant collection',
    `vector_id` varchar(128) DEFAULT NULL COMMENT 'Qdrant point ID',
    `indexed_at` datetime DEFAULT NULL COMMENT '最近索引时间',
    `occurred_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '事实发生时间',
    `archived_at` datetime DEFAULT NULL COMMENT '归档时间',
    `masked_at` datetime DEFAULT NULL COMMENT '脱敏时间',
    `deleted_at` datetime DEFAULT NULL COMMENT '删除或撤销时间',
    `code` varchar(255) DEFAULT NULL COMMENT '编码',
    `description` varchar(255) DEFAULT NULL COMMENT '说明',
    `create_date_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_name` varchar(255) DEFAULT NULL COMMENT '创建人',
    `modify_date_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `modify_name` varchar(255) DEFAULT NULL COMMENT '修改人',
    `is_delete` bit(1) DEFAULT b'0' COMMENT '删除状态',
    `label` varchar(255) DEFAULT NULL COMMENT '标签',
    `sorting` int DEFAULT '0' COMMENT '排序',
    `version` int DEFAULT '1' COMMENT '版本号',
    `tenant_id` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '100' COMMENT 'Kellen 内部租户ID',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_memory_long_fact_key_status` (`patient_id`, `source_tenant_id`, `memory_key`, `status`),
    KEY `idx_ai_memory_long_fact_patient_status` (`patient_id`, `source_tenant_id`, `status`, `occurred_at`),
    KEY `idx_ai_memory_long_fact_source` (`source_type`, `source_id`),
    KEY `idx_ai_memory_long_fact_embedding` (`embedding_status`, `modify_date_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='AI 患者长期记忆权威事实';

CREATE TABLE IF NOT EXISTS `ai_memory_candidate` (
    `id` varchar(64) NOT NULL COMMENT '主键ID',
    `caller` varchar(64) NOT NULL COMMENT '调用方',
    `purpose` varchar(128) DEFAULT NULL COMMENT '写入目的',
    `trace_id` varchar(128) DEFAULT NULL COMMENT '调用链追踪ID',
    `user_id` varchar(64) DEFAULT NULL COMMENT '调用方用户ID',
    `tenant_id` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '100' COMMENT 'Kellen 内部租户ID',
    `source_tenant_id` varchar(64) NOT NULL COMMENT '来源业务租户ID',
    `patient_id` varchar(64) NOT NULL COMMENT '患者ID',
    `conversation_id` varchar(128) DEFAULT NULL COMMENT '来源会话ID',
    `source_type` varchar(64) DEFAULT NULL COMMENT '来源类型',
    `source_id` varchar(128) DEFAULT NULL COMMENT '来源业务ID',
    `memory_type` varchar(64) NOT NULL COMMENT '记忆类型',
    `memory_key` varchar(160) NOT NULL COMMENT '稳定记忆键',
    `title` varchar(255) DEFAULT NULL COMMENT '候选标题',
    `content` longtext NOT NULL COMMENT '候选内容',
    `facts_json` longtext DEFAULT NULL COMMENT '结构化事实 JSON',
    `confidence` double NOT NULL DEFAULT '0' COMMENT '候选置信度',
    `requires_human_review` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否需要人工确认',
    `sensitivity_level` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '敏感级别',
    `authorization_scope` varchar(128) DEFAULT NULL COMMENT '授权范围',
    `review_status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '审核状态',
    `rejection_reason` varchar(500) DEFAULT NULL COMMENT '拒绝原因',
    `promoted_memory_id` varchar(64) DEFAULT NULL COMMENT '晋升后的长期记忆ID',
    `occurred_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '事实发生时间',
    `reviewed_at` datetime DEFAULT NULL COMMENT '审核时间',
    `code` varchar(255) DEFAULT NULL COMMENT '编码',
    `description` varchar(255) DEFAULT NULL COMMENT '说明',
    `create_date_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_name` varchar(255) DEFAULT NULL COMMENT '创建人',
    `modify_date_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `modify_name` varchar(255) DEFAULT NULL COMMENT '修改人',
    `is_delete` bit(1) DEFAULT b'0' COMMENT '删除状态',
    `label` varchar(255) DEFAULT NULL COMMENT '标签',
    `sorting` int DEFAULT '0' COMMENT '排序',
    `version` int DEFAULT '1' COMMENT '版本号',
    PRIMARY KEY (`id`),
    KEY `idx_ai_memory_candidate_patient_status` (`patient_id`, `source_tenant_id`, `review_status`, `occurred_at`),
    KEY `idx_ai_memory_candidate_source` (`source_type`, `source_id`),
    KEY `idx_ai_memory_candidate_trace` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='AI 候选记忆写入';

CREATE TABLE IF NOT EXISTS `ai_memory_event` (
    `id` varchar(64) NOT NULL COMMENT '主键ID',
    `operation` varchar(64) NOT NULL COMMENT '操作类型',
    `target_type` varchar(64) DEFAULT NULL COMMENT '目标类型',
    `target_id` varchar(128) DEFAULT NULL COMMENT '目标ID',
    `caller` varchar(64) DEFAULT NULL COMMENT '调用方',
    `purpose` varchar(128) DEFAULT NULL COMMENT '调用目的',
    `trace_id` varchar(128) DEFAULT NULL COMMENT '调用链追踪ID',
    `user_id` varchar(64) DEFAULT NULL COMMENT '操作用户ID',
    `tenant_id` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '100' COMMENT 'Kellen 内部租户ID',
    `source_tenant_id` varchar(64) DEFAULT NULL COMMENT '来源业务租户ID',
    `patient_id` varchar(64) DEFAULT NULL COMMENT '患者ID',
    `reason` varchar(500) DEFAULT NULL COMMENT '操作原因',
    `result` varchar(64) DEFAULT NULL COMMENT '操作结果',
    `detail_json` longtext DEFAULT NULL COMMENT '审计详情 JSON',
    `code` varchar(255) DEFAULT NULL COMMENT '编码',
    `description` varchar(255) DEFAULT NULL COMMENT '说明',
    `create_date_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_name` varchar(255) DEFAULT NULL COMMENT '创建人',
    `modify_date_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `modify_name` varchar(255) DEFAULT NULL COMMENT '修改人',
    `is_delete` bit(1) DEFAULT b'0' COMMENT '删除状态',
    `label` varchar(255) DEFAULT NULL COMMENT '标签',
    `sorting` int DEFAULT '0' COMMENT '排序',
    `version` int DEFAULT '1' COMMENT '版本号',
    PRIMARY KEY (`id`),
    KEY `idx_ai_memory_event_patient_time` (`patient_id`, `source_tenant_id`, `create_date_time`),
    KEY `idx_ai_memory_event_operation` (`operation`, `create_date_time`),
    KEY `idx_ai_memory_event_trace` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='AI 记忆审计事件';

CREATE TABLE IF NOT EXISTS `ai_memory_vector_task` (
    `id` varchar(64) NOT NULL COMMENT '主键ID',
    `task_type` varchar(32) NOT NULL COMMENT '任务类型 UPSERT/DELETE/REBUILD',
    `memory_id` varchar(64) DEFAULT NULL COMMENT '长期记忆ID',
    `patient_id` varchar(64) DEFAULT NULL COMMENT '患者ID',
    `source_tenant_id` varchar(64) DEFAULT NULL COMMENT '来源业务租户ID',
    `collection_name` varchar(128) DEFAULT NULL COMMENT 'Qdrant collection',
    `vector_id` varchar(128) DEFAULT NULL COMMENT 'Qdrant point ID',
    `payload_json` longtext DEFAULT NULL COMMENT '派生索引 payload',
    `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '任务状态',
    `attempts` int NOT NULL DEFAULT '0' COMMENT '执行次数',
    `next_retry_at` datetime DEFAULT NULL COMMENT '下次重试时间',
    `error_message` varchar(1000) DEFAULT NULL COMMENT '错误信息',
    `code` varchar(255) DEFAULT NULL COMMENT '编码',
    `description` varchar(255) DEFAULT NULL COMMENT '说明',
    `create_date_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_name` varchar(255) DEFAULT NULL COMMENT '创建人',
    `modify_date_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `modify_name` varchar(255) DEFAULT NULL COMMENT '修改人',
    `is_delete` bit(1) DEFAULT b'0' COMMENT '删除状态',
    `label` varchar(255) DEFAULT NULL COMMENT '标签',
    `sorting` int DEFAULT '0' COMMENT '排序',
    `version` int DEFAULT '1' COMMENT '版本号',
    `tenant_id` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '100' COMMENT 'Kellen 内部租户ID',
    PRIMARY KEY (`id`),
    KEY `idx_ai_memory_vector_task_status` (`status`, `next_retry_at`, `create_date_time`),
    KEY `idx_ai_memory_vector_task_memory` (`memory_id`, `status`),
    KEY `idx_ai_memory_vector_task_patient` (`patient_id`, `source_tenant_id`, `task_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='AI 记忆 Qdrant 派生索引任务';

CREATE TABLE IF NOT EXISTS `ai_memory_retrieval_eval` (
    `id` varchar(64) NOT NULL COMMENT '主键ID',
    `trace_id` varchar(128) DEFAULT NULL COMMENT '调用链追踪ID',
    `caller` varchar(64) DEFAULT NULL COMMENT '调用方',
    `purpose` varchar(128) DEFAULT NULL COMMENT '召回目的',
    `source_tenant_id` varchar(64) DEFAULT NULL COMMENT '来源业务租户ID',
    `patient_id` varchar(64) DEFAULT NULL COMMENT '患者ID',
    `conversation_id` varchar(128) DEFAULT NULL COMMENT '会话ID',
    `query_text` varchar(1000) DEFAULT NULL COMMENT '召回查询文本',
    `max_items` int DEFAULT NULL COMMENT '最大条数',
    `max_tokens` int DEFAULT NULL COMMENT '最大 token 预算',
    `short_hit_count` int NOT NULL DEFAULT '0' COMMENT '短记忆命中数',
    `sql_hit_count` int NOT NULL DEFAULT '0' COMMENT 'MySQL 长记忆命中数',
    `vector_hit_count` int NOT NULL DEFAULT '0' COMMENT 'Qdrant 命中数',
    `returned_count` int NOT NULL DEFAULT '0' COMMENT '返回条数',
    `latency_ms` bigint NOT NULL DEFAULT '0' COMMENT '召回耗时毫秒',
    `result_message` varchar(1000) DEFAULT NULL COMMENT '召回结果摘要',
    `code` varchar(255) DEFAULT NULL COMMENT '编码',
    `description` varchar(255) DEFAULT NULL COMMENT '说明',
    `create_date_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_name` varchar(255) DEFAULT NULL COMMENT '创建人',
    `modify_date_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    `modify_name` varchar(255) DEFAULT NULL COMMENT '修改人',
    `is_delete` bit(1) DEFAULT b'0' COMMENT '删除状态',
    `label` varchar(255) DEFAULT NULL COMMENT '标签',
    `sorting` int DEFAULT '0' COMMENT '排序',
    `version` int DEFAULT '1' COMMENT '版本号',
    `tenant_id` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '100' COMMENT 'Kellen 内部租户ID',
    PRIMARY KEY (`id`),
    KEY `idx_ai_memory_retrieval_eval_patient_time` (`patient_id`, `source_tenant_id`, `create_date_time`),
    KEY `idx_ai_memory_retrieval_eval_trace` (`trace_id`),
    KEY `idx_ai_memory_retrieval_eval_caller` (`caller`, `purpose`, `create_date_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='AI 记忆召回评估记录';
